image: Visual Studio 2017

version: 0.0.0.{build}
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip

build_script:
  - appveyor.cmd

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_tags: true

artifacts:
- path: build\Release\**\*.nupkg
  name: nuget
